### PR TITLE
Add Zen 4 CPU ID

### PR DESCRIPTION
**Pull request by Etaash-mathamsetty**
also family 19, so this is just a simple 2 line addition

### CODE REVIEW

**Comment by Etaash-mathamsetty** [comment]
@BoukeHaarsma23 Could you merge this pls?

**Comment by BoukeHaarsma23** [comment]
Have you tested this? I don't have any zen4 system, so I'm not able to test this. Can you show me the sensors output? And are the numbers reasonable?

**Comment by Etaash-mathamsetty** [comment]
> Have you tested this? I don't have any zen4 system, so I'm not able to test this. Can you show me the sensors output? And are the numbers reasonable?

yes I tested power draw through mangohud. I'm pretty sure it grabs temps and stuff from zenergy as well and it all looks correct to me

**Comment by Etaash-mathamsetty** [comment]
image

**Pull request merged**
