### PR TITLE
fixup: Zen4 features 64-bit RAPL energy MSRs

### PR DESCRIPTION
**Pull request by NiLuJe**
Meaning we can skip the accumulator kthread on those CPUs.

Tested on a 7950X3D.

### CODE REVIEW

**Comment by BoukeHaarsma23** [comment]
hey, thanks for your work. Could you rebase and only make a PR with the zen4 related stuff? Thanks :)

**Comment by NiLuJe** [comment]
Done ;).

**Comment by NiLuJe** [comment]
And I've split the minor 6.9+ topo cleanup in a separate PR

**Comment by BoukeHaarsma23** [comment]
thanks

**Pull request merged**
